### ISSUE TITLE
Restrict Adaptive Device Size to Width (ignore height)

### ISSUE THREAD

**Issue by Mrkbingham** [tableau/embedding-api-v3-guide#4]
[Right now](https://help.tableau.com/current/pro/desktop/en-us/dashboards_dsd_create.htm#confirm-which-layout--a-device-will-display), Tableau chooses device size based on both **height** and **width** of the available browser space.  Can you change this to just width?  

I struggle to think of an application where it would be necessary to have a mobile view on a wide-yet-short monitor, and believe the majority of responsive/mobile design is based on width and ignores height

**Comment by Kovner** [comment]
Hrmm, well the current behavior is actually just in non-Embedded. In the JSAPI v2, we don't intelligently detect the form factor and choose the Device Specific Dashboard for you. Instead, you can write the JS to do that. So you have a workaround today, but in v3 we plan on doing more intelligent browser-size detection and DSD choosing. We are still working out how to do that which is why its not in the migration guide.

**Comment by Mrkbingham** [comment]
My understanding here is that there's no difference between directly hitting Tableau Server and the v2 JS API.  I suppose you could prevent the iFrame from ever being smaller than 500/800px tall with JS/CSS to prevent that, but there are occasions where we need to embed smaller iFrames than that.  Noted as a possible workaround, but this is probably more of a request to add width-only device detection in Tableau since height doesn't seem to be very standard across the web.  

Excited about the updated device detection though.
